/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ScaleRouteImport } from './routes/scale'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as ValidationRouteImport } from './routes/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaleRoute = ScaleRouteImport.update({
  id: '/scale',
  path: '/scale',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/scale': typeof ScaleRoute
  '/trace': typeof TraceRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/scale': typeof ScaleRoute
  '/trace': typeof TraceRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/scale': typeof ScaleRoute
  '/trace': typeof TraceRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digital-twin'
    | '/intelligence'
    | '/operations'
    | '/scale'
    | '/trace'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digital-twin'
    | '/intelligence'
    | '/operations'
    | '/scale'
    | '/trace'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/digital-twin'
    | '/intelligence'
    | '/operations'
    | '/scale'
    | '/trace'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  IntelligenceRoute: typeof IntelligenceRoute
  OperationsRoute: typeof OperationsRoute
  ScaleRoute: typeof ScaleRoute
  TraceRoute: typeof TraceRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scale': {
      id: '/scale'
      path: '/scale'
      fullPath: '/scale'
      preLoaderRoute: typeof ScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  IntelligenceRoute: IntelligenceRoute,
  OperationsRoute: OperationsRoute,
  ScaleRoute: ScaleRoute,
  TraceRoute: TraceRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
